USE [master]
GO
DROP DATABASE [CrabMetadata]
GO
CREATE DATABASE [CrabMetadata]
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'CrabMetadata', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CrabMetadata].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [CrabMetadata] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CrabMetadata] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CrabMetadata] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CrabMetadata] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CrabMetadata] SET ARITHABORT OFF 
GO
ALTER DATABASE [CrabMetadata] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CrabMetadata] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [CrabMetadata] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CrabMetadata] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CrabMetadata] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CrabMetadata] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CrabMetadata] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CrabMetadata] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CrabMetadata] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CrabMetadata] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CrabMetadata] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CrabMetadata] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CrabMetadata] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CrabMetadata] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CrabMetadata] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CrabMetadata] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CrabMetadata] SET  READ_WRITE 
GO
ALTER DATABASE [CrabMetadata] SET RECOVERY FULL 
GO
ALTER DATABASE [CrabMetadata] SET  MULTI_USER 
GO
ALTER DATABASE [CrabMetadata] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CrabMetadata] SET DB_CHAINING OFF 